CATALOGMGR_LIB_OBJECTS= \
	$(CATALOG_MGR_BASE_DIR)/src/AggregateBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/Application.o \
	$(CATALOG_MGR_BASE_DIR)/src/Arc.o \
	$(CATALOG_MGR_BASE_DIR)/src/ArcRecord.o \
	$(CATALOG_MGR_BASE_DIR)/src/Box.o \
	$(CATALOG_MGR_BASE_DIR)/src/BoxRecord.o \
	$(CATALOG_MGR_BASE_DIR)/src/BSortBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/CatalogManager.o \
	$(CATALOG_MGR_BASE_DIR)/src/CompositeType.o \
	$(CATALOG_MGR_BASE_DIR)/src/CompositeTypeRecord.o \
	$(CATALOG_MGR_BASE_DIR)/src/DataInputStream.o \
	$(CATALOG_MGR_BASE_DIR)/src/DataOutputStream.o \
	$(CATALOG_MGR_BASE_DIR)/src/DropBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/FilterBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/HelloWorldBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/IntegerArrayDbt.o \
	$(CATALOG_MGR_BASE_DIR)/src/IntegerDbt.o \
	$(CATALOG_MGR_BASE_DIR)/src/JoinBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/LRReadRelationBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/LRUpdateRelationBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/MapBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/PortRecord.o \
	$(CATALOG_MGR_BASE_DIR)/src/QoS.o \
	$(CATALOG_MGR_BASE_DIR)/src/QueryNetwork.o \
	$(CATALOG_MGR_BASE_DIR)/src/RandomPoint.o \
	$(CATALOG_MGR_BASE_DIR)/src/ReadRelationBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/Relation.o \
	$(CATALOG_MGR_BASE_DIR)/src/RelationEnvironment.o \
	$(CATALOG_MGR_BASE_DIR)/src/ResampleBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/RestreamBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/SourceStream.o \
	$(CATALOG_MGR_BASE_DIR)/src/Stream.o \
	$(CATALOG_MGR_BASE_DIR)/src/TypeFieldRecord.o \
	$(CATALOG_MGR_BASE_DIR)/src/TypeManager.o \
	$(CATALOG_MGR_BASE_DIR)/src/UnionBox.o \
	$(CATALOG_MGR_BASE_DIR)/src/UpdateRelationBox.o
